version: "3"

dotenv: ["./subgraph.env"]

tasks:

  docker-build:
    desc: "Build subgraph Docker image on defined node version base (default: 16-slim)."
    cmds:
      - docker build -t setprotocol/subgraph:node-${NODE_VER} -f docker/Dockerfile --build-arg NODE_VER=$NODE_VER .
    env:
      NODE_VER: "{{.NODE_VER}}"

  gen-abi:
    desc: "Pull latest Set Protocol ABIs into the build env."
    cmds:
      # Note the following command requires node ver 16 or below (only 12 and 16 tested working)
      - docker run -v $(pwd)/abis:/subgraph/abis -v $(pwd)/scripts:/subgraph/scripts -w /subgraph --rm setprotocol/subgraph:node-16 bash scripts/update-abis.sh

  deploy:
    desc: "Build and deploy subgraph."
    dir: docker/
    cmds:
      - docker-compose up
    env:
      NODE_VER: "{{.NODE_VER}}"
      IPFS_IP: "{{.IPFS_IP}}"
      NODE_IP: "{{.NODE_IP}}"
      NETWORK: "{{.NETWORK}}"
      ACCESS_TOKEN: "{{.ACCESS_TOKEN}}"
      SUBGRAPH_VER_LABEL: "{{.SUBGRAPH_VER_LABEL}}"

  deploy-local:
    desc: "Build and deploy subgraph on local network."
    cmds:
      - task: deploy
        vars:
          ACCESS_TOKEN: "{{.ACCESS_TOKEN}}"
          IPFS_IP: "http://{{.IPFS_LOCAL}}:{{.IPFS_PORT}}"
          NODE_IP: "http://{{.NODE_LOCAL}}:{{.NODE_PORT}}"
          NETWORK: "hardhat"

  deploy-hosted:
    desc: "Build and deploy subgraph on Hosted Service."
    cmds:
      - task: deploy
        vars: 
          IPFS_IP: "https://{{.IPFS_HOSTED}}"
          NODE_IP: "https://{{.NODE_HOSTED}}"
          NETWORK: "{{.NETWORK}}"
