version: '3'

services:
  setprotocol-subgraph:
    image: setprotocol/subgraph:node-${NODE_VER}
    environment:
      IPFS_IP: ${IPFS_IP}
      NODE_IP: ${NODE_IP}
      NETWORK: ${NETWORK}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      SUBGRAPH_VER_LABEL: ${SUBGRAPH_VER_LABEL}
    ports:
      - 5001
      - 8020
    volumes:
      - ../:/subgraph
      - setprotocol-subgraph-node_modules:/subgraph/node_modules
    working_dir: /subgraph
    command: "sh ./scripts/deploy.sh"

volumes:
  setprotocol-subgraph-node_modules:
    external: false
