version: '3'

services:

  hardhat-build:
    image: ${HARDHAT_IMAGE_NAME}:node-${NODE_VER}
    environment:
      HARDHAT_PORT: ${HARDHAT_PORT:-"8545"}
      TEST_SCRIPT: ${TEST_SCRIPT:-""}
    working_dir: /app
    volumes:
      - ../scripts:/app/scripts
      - hardhat:/app

volumes:
  hardhat:
    external: false
